SFLOWUS_FIELDDATA(SFLOWUS_ATTR_IFINDEX, 0, 0, "ifIndex") 
SFLOWUS_FIELDDATA(SFLOWUS_ATTR_COUNTERS_GENERIC, SFLCOUNTERS_GENERIC, 0, "generic counters") 
SFLOWUS_FIELDDATA(SFLOWUS_ATTR_COUNTERS_LACP, SFLCOUNTERS_LACP, 0, "LACP counters") 
SFLOWUS_FIELDDATA(SFLOWUS_ATTR_PORTNAME, SFLCOUNTERS_PORTNAME, 0, "port name") 
